/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccordionIndexRouteImport } from './routes/accordion.index'

const AccordionIndexRoute = AccordionIndexRouteImport.update({
  id: '/accordion/',
  path: '/accordion/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/accordion': typeof AccordionIndexRoute
}
export interface FileRoutesByTo {
  '/accordion': typeof AccordionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/accordion/': typeof AccordionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/accordion'
  fileRoutesByTo: FileRoutesByTo
  to: '/accordion'
  id: '__root__' | '/accordion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccordionIndexRoute: typeof AccordionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accordion/': {
      id: '/accordion/'
      path: '/accordion'
      fullPath: '/accordion'
      preLoaderRoute: typeof AccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AccordionIndexRoute: AccordionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
