/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TooltipRouteImport } from './routes/tooltip'
import { Route as TabmenuRouteImport } from './routes/tabmenu'
import { Route as AccordionIndexRouteImport } from './routes/accordion.index'

const TooltipRoute = TooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const TabmenuRoute = TabmenuRouteImport.update({
  id: '/tabmenu',
  path: '/tabmenu',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionIndexRoute = AccordionIndexRouteImport.update({
  id: '/accordion/',
  path: '/accordion/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/tabmenu': typeof TabmenuRoute
  '/tooltip': typeof TooltipRoute
  '/accordion': typeof AccordionIndexRoute
}
export interface FileRoutesByTo {
  '/tabmenu': typeof TabmenuRoute
  '/tooltip': typeof TooltipRoute
  '/accordion': typeof AccordionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/tabmenu': typeof TabmenuRoute
  '/tooltip': typeof TooltipRoute
  '/accordion/': typeof AccordionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tabmenu' | '/tooltip' | '/accordion'
  fileRoutesByTo: FileRoutesByTo
  to: '/tabmenu' | '/tooltip' | '/accordion'
  id: '__root__' | '/tabmenu' | '/tooltip' | '/accordion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabmenuRoute: typeof TabmenuRoute
  TooltipRoute: typeof TooltipRoute
  AccordionIndexRoute: typeof AccordionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tooltip': {
      id: '/tooltip'
      path: '/tooltip'
      fullPath: '/tooltip'
      preLoaderRoute: typeof TooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabmenu': {
      id: '/tabmenu'
      path: '/tabmenu'
      fullPath: '/tabmenu'
      preLoaderRoute: typeof TabmenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion/': {
      id: '/accordion/'
      path: '/accordion'
      fullPath: '/accordion'
      preLoaderRoute: typeof AccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TabmenuRoute: TabmenuRoute,
  TooltipRoute: TooltipRoute,
  AccordionIndexRoute: AccordionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
