export const routes = {
  '/': 'views/home.html',
  '/accordion': 'views/accordion.html',
  '/tabMenu': 'views/tabMenu.html',
  '/tooltip': 'views/tooltip.html',
  '/textBox': 'views/textBox.html',
  '/lineClamp': 'views/lineClamp.html',
  '/lazyLoading': 'views/lazyLoading.html',
  '/lazyLoading/1_r': 'views/lazyLoading_1_r.html',
  '/lazyLoading/2_v': 'views/lazyLoading_2_v.html',
  '/lazyLoading/3_r': 'views/lazyLoading_3_r.html',
  '/infiniteScroll': 'views/infiniteScroll.html',
  '/infiniteScroll/react': 'views/infiniteScroll_react.html',
  '/infiniteScroll/vanilla': 'views/infiniteScroll_vanilla.html',
  '/scrollBox': 'views/scrollBox.html',
  '/scrollSpy': 'views/scrollSpy.html',
  '/scrollSpy/1_r': 'views/scrollSpy_1_r.html',
  '/scrollSpy/2_r': 'views/scrollSpy_2_r.html',
  '/scrollSpy/3_v': 'views/scrollSpy_3_v.html',
  '/scrollSpy/4_r': 'views/scrollSpy_4_r.html',
  '/snackbar': 'views/snackbar.html',
  '/modal': 'views/modal.html',
  '/popover': 'views/popover.html',
  '/imageSlide': 'views/imageSlide.html',
  '/carousel': 'views/carousel.html',
  '/gallery': 'views/gallery.html',
  '/selectBox': 'views/selectBox.html',
  '/autoComplete': 'views/autoComplete.html',
  '/dnd': 'views/dnd.html',
  '404': 'views/404.html',
};

export const gnbRootList = [
  { link: '/accordion', name: 'Accordion', key: 'accordion' },
  { link: '/tabMenu', name: 'Tab Menu', key: 'tabMenu' },
  { link: '/tooltip', name: 'Tooltip', key: 'tooltip' },
  { link: '/textBox', name: 'Text Box', key: 'textBox' },
  { link: '/lazyLoading', name: 'Lazy Loading', key: 'lazyLoading' },
  { link: '/infiniteScroll', name: 'Infinite Scroll', key: 'infiniteScroll' },
  { link: '/scrollBox', name: 'Scroll Box', key: 'scrollBox' },
  { link: '/scrollSpy', name: 'Scroll Spy', key: 'scrollSpy' },
  { link: '/snackbar', name: 'Snackbar', key: 'snackbar' },
  { link: '/modal', name: 'Modal', key: 'modal' },
  { link: '/popover', name: 'Popover', key: 'popover' },
  { link: '/imageSlide', name: 'Image Slide', key: 'imageSlide' },
  { link: '/carousel', name: 'Carousel', key: 'carousel' },
  { link: '/gallery', name: 'Gallery', key: 'gallery' },
  { link: '/selectBox', name: 'Select Box', key: 'selectBox' },
  { link: '/autoComplete', name: 'Auto Complete', key: 'autoComplete' },
  { link: '/dnd', name: 'Drag & Drop (DND)', key: 'dnd' },
];